
INSERT [dbo].[Status] ([Id], [Name], [Enable]) VALUES (1, N'Ожидает обработки', 1)
INSERT [dbo].[Status] ([Id], [Name], [Enable]) VALUES (2, N'Согласован', 1)
INSERT [dbo].[Status] ([Id], [Name], [Enable]) VALUES (3, N'Отменен', 1)
INSERT [dbo].[Status] ([Id], [Name], [Enable]) VALUES (4, N'Выполнен', 1)

INSERT [dbo].[AttachmentType] ([Id], [Name]) VALUES (1, N'Photo')
INSERT [dbo].[AttachmentType] ([Id], [Name]) VALUES (2, N'Video')
INSERT [dbo].[AttachmentType] ([Id], [Name]) VALUES (3, N'Audio')
INSERT [dbo].[AttachmentType] ([Id], [Name]) VALUES (4, N'Voice')
INSERT [dbo].[AttachmentType] ([Id], [Name]) VALUES (5, N'VideoNone')
INSERT [dbo].[AttachmentType] ([Id], [Name]) VALUES (6, N'Document')
INSERT [dbo].[Currency] ([Id], [Name], [ShortName], [Code]) VALUES (1, N'Рубль', N'руб.', N'RUB')
INSERT [dbo].[Currency] ([Id], [Name], [ShortName], [Code]) VALUES (2, N'Гривна', N'грн.', N'UAH')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (1, N'Наличными при получении', 1, NULL)
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (2, N'QIWI', 0, N'Руб.')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (3, N'Litecoin', 0, N'ltc')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (4, N'Bitcoin Cash', 0, N'bch')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (5, N'Doge', 0, N'doge')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (6, N'Bitcoin', 0, N'btc')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (7, N'Картой (экв. Яндекс Касса)', 0, N'Руб.')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (8, N'Dash', 0, N'DASH')
INSERT [dbo].[PaymentType] ([Id], [Name], [Enable], [Code]) VALUES (9, N'Zcash', 0, N'Zcash')
SET IDENTITY_INSERT [dbo].[Units] ON 

INSERT [dbo].[Units] ([Id], [Name], [ShortName]) VALUES (1, N'Штуки', N'шт.')
INSERT [dbo].[Units] ([Id], [Name], [ShortName]) VALUES (2, N'Граммы', N'г.')
INSERT [dbo].[Units] ([Id], [Name], [ShortName]) VALUES (3, N'Килограммы', N'кг.')
INSERT [dbo].[Units] ([Id], [Name], [ShortName]) VALUES (4, N'Литры', N'л.')
INSERT [dbo].[Units] ([Id], [Name], [ShortName]) VALUES (5, N'Метр', N'м.')
INSERT [dbo].[Units] ([Id], [Name], [ShortName]) VALUES (6, N'Сантиметр', N'см.')
SET IDENTITY_INSERT [dbo].[Units] OFF
